name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: make
      - name: Replace version with tag
        run: sed -i "s/v0.0.0/${{ github.event.release.tag_name }}/g" nfpm.yml
      - name: Create deb
        run: nfpm package --packager deb --config nfpm.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: caddy_*.deb
